### ISSUE TITLE
Support for python extra paths

### ISSUE THREAD

**Issue by danstewart** [teticio/python-envy#1]
Hi,

First of all, thanks for this extension - it's really helpful.

We have ran into a similar issue which I think can be fixed in a similar way.

The quick fix for imports always tries to import from the monorepo root.
We can workaround this by setting `python.atuoComplete.extraPaths` and `python.analysis.extraPaths` to contain each app folder but then it will suggest cross app imports.

So two questions
1. Have you ran into this and found a better solution?
2. If it is possible to handle this in the same way do you think it's within scope for this extension and would you welcome a PR or would it be better for it to be a separate extension?

Thanks

**Comment by teticio** [comment]
HI thanks for reaching out. I have to confess I don't fully understand the issue you are trying to resolve. Can you try to explain it in more detail? I'd also be happy to consider a PR, as long as it makes sense for what is a rather simple extension.

**Comment by danstewart** [comment]
Hey Robert,

If we have a folder structure of `mono/app1` and `mono/app2` then VSCode tries to resolve all imports from the root, like `from mono.app1.lib import foo` but we actually want `from app1.lib import foo`.

We're new to using a mono repo so we might just be doing something wrong.

No harm done if I raise the PR and you decide against it then it's easy enough to take the PR and make a separate extension.

**Comment by teticio** [comment]
OK, if you do that then please also provide a minimal example that shows what you describe above. I wonder if you shouldn't be doing something like this instead: see libs in https://github.com/langchain-ai/langchain. This repo is intended more for having multiple virtualenvs hanging off the same root monorepo. Each of these can correspond to a package or a service that may inherit some dependencies from the parent (this is a nice feature of poetry) and have some dependencies of its own. Your example is more about relative imports and I think doing this in an automatic way could lead to confusion (e.g., picking up the wrong package if there are several of the same name at different levels). I would make this explicit in the project settings (as you appear to have done). WDYT?

**Comment by danstewart** [comment]
Sorry, I don't think I've explained clearly.

It's not a relative import, the root of each app is `app1` and `app2` and the root of the repository is `mono`, so when VSCode tries to import as `from mono.app1.lib import foo` it errors at runtime.

We use docker and copy in from the app folder into the container so `mono` doesn't exist.

Though you're right it does seem a little confusing as VSCode would allow us to import across apps which would also fail at run time.

I think multi root workspaces partially helps here but that came with other issues (which I've forgotten).

I'm away from home for a few days but I'll take another look at the multi root workspace when I'm home and figure out which approaches come with which issues.

**Comment by danstewart** [comment]
Sorry, not had time to look into this more.
It doesn't seem to be causing us any issues (so far...) so not too much of a priority.

I'll close this down and raise a PR if it becomes more of an issue for us 🙂 

Thanks again for the extension.
